# Generated by Django 5.2.7 on 2025-11-13 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScoreCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=10, verbose_name='点数')),
                ('posted_at', models.DateTimeField(auto_now_add=True, verbose_name='登録日時')),
                ('category', models.CharField(choices=[('language', '国語'), ('math', '数学'), ('english', '英語'), ('science', '科学'), ('history', '歴史')], max_length=50, verbose_name='カテゴリ')),
            ],
        ),
    ]
