# Generated by Django 5.2.7 on 2025-11-19 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scorecategory',
            old_name='title',
            new_name='score',
        ),
    ]
